/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.MedicineCatalog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author whh
 */
public class CatalogJPanel extends javax.swing.JPanel {

    private Application application;
    DefaultTableModel medTableModel;
    /**
     * Creates new form CatalogJPanel
     */
    public CatalogJPanel() {
        initComponents();
    }
    
    CatalogJPanel(Application application) {
        initComponents();
        this.application = application;
        this.medTableModel = (DefaultTableModel) medicineCatalog.getModel();
        displayMedicineCatalog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        medicineCatalog = new javax.swing.JTable();
        name = new javax.swing.JTextField();
        dosage = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicineCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Dosage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        medicineCatalog.setEnabled(false);
        jScrollPane1.setViewportView(medicineCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 375, 200));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 120, 20));

        dosage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosageActionPerformed(evt);
            }
        });
        add(dosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, -1));

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void dosageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosageActionPerformed
    
    private void nameActionFocusLost(java.awt.event.ActionEvent evt){
        String name = this.name.getText();
        Boolean isUnique = this.application.getCatalog().checkIfMedicineUnique(name);
        if(isUnique){
        }
        else{
            this.name.setText("");
            JOptionPane.showMessageDialog(null, "Already exist");
        }
    }
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        String name = this.name.getText();
        String dosage = this.dosage.getText();
        
        MedicineCatalog catalog = this.application.getCatalog();
        catalog.createMedicine(name, Double.valueOf(dosage));
        

        displayMedicineCatalog();
    }//GEN-LAST:event_addbtnActionPerformed
    
    public void displayMedicineCatalog(){
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
        if(medicines.size() > 0){
            medTableModel.setRowCount(0);
            for(Medicine med: medicines){
                Object row[] = new Object[2];
                row[0] = med;
                row[1] = med.getDosage();
                medTableModel.addRow(row);
            }
        }
    }
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        int selectedRow = medicineCatalog.getSelectedRow();
        if(selectedRow >= 0){
            Medicine med = (Medicine) medicineCatalog.getValueAt(selectedRow, 0);
            this.application.getCatalog().removeMedicine(med.getMedicineName());
            displayMedicineCatalog();
        }
        else{
            
        }
    }//GEN-LAST:event_deletebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField dosage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicineCatalog;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
